@startuml


'CNC IDE'

class FileIDE{
    textAreaOne;
    textAreaTwo;
    textAreaTree;
    parentDiv;
    chooseFileButton: HTMLButtonElement;
    loadFileButton: HTMLButtonElement;
    loadFileDiv: HTMLDivElement
    input: HTMLInputElement;
    ProgramTypeSelection: HTMLFormElement;
    IDE: IDE;

}

class CanalAdapter{
    textAreaCode: HTMLTextAreaElement;
    textAreaLineNumber: HTMLTextAreaElement;
    textAreaTimeLine: HTMLTextAreaElement
    keyElementList: string[] : []
    id: number;

}


class Canal{
    textAreaCode: HTMLTextAreaElement;
    textAreaLineNumber: HTMLTextAreaElement;
    textAreaTimeLine: HTMLTextAreaElement
    keyElementList: string[] : []
    id: number;

}

class aceEditor{
    textAreaCode: HTMLTextAreaElement;
    textAreaLineNumber: HTMLTextAreaElement;
    textAreaTimeLine: HTMLTextAreaElement
    keyElementList: string[] : []
    id: number;

}


class 3Dview{
    plot()
}


class Observer{
    update()
}

class Observable{
    update()
    add(Observer)
    updated()
}


class IDE{
    parentDiv;
    view3d: any;
    static canals: Array<Canal> = [];
    rowWidth = 50.0
    printConsole;
    readonly _controllList : ['FANUC TURN', 'STAR SB-12RG']
    static timeTable: any;
    static selectedMachine: string
    waitTable : HTMLTableElement
    scrollSyncFunction : function
}

class ViewObjectCreator{
    createPlotButton(divElement)
}

class IDEControll
class IDEModel
class TreeJS

IDE .> CanalAdapter : uses
IDE ..> ViewObjectCreator : uses
Canal .> aceEditor : uses

CanalAdapter <|-- Canal : uses


IDE .> 3Dview : uses
Canal ..> 3Dview : uses
IDE ..|> Observer : uses
Canal ..|> Observable : uses 
CanalAdapter ..|> Observable : uses 
3Dview ..> TreeJS : uses

FileIDE ..> IDE : uses